import { Controller, Post, Body, HttpCode, HttpStatus, Logger } from '@nestjs/common';
import { MemberService } from '../../domains/member/services/member.service';
import { JwtService } from '../../infrastructure/auth/jwt.service';
import { 
  MemberRegisterDto, 
  MemberLoginDto, 
  MemberLoginResponseDto,
  MemberProfileResponseDto 
} from '../../domains/member/dto/member-auth.dto';
import { ApiSuccessResponse } from '../../common/interfaces/api-response.interface';

@Controller('member/auth')
export class MemberAuthController {
  private readonly logger = new Logger(MemberAuthController.name);

  constructor(
    private readonly memberService: MemberService,
    private readonly jwtService: JwtService,
  ) {}

  @Post('register')
  @HttpCode(HttpStatus.CREATED)
  async register(@Body() registerDto: MemberRegisterDto): Promise<ApiSuccessResponse<MemberProfileResponseDto>> {
    this.logger.log(`Member registration attempt for: ${registerDto.email}`);

    const member = await this.memberService.registerMember({
      email: registerDto.email,
      username: registerDto.username,
      password: registerDto.password,
      firstName: registerDto.firstName,
      lastName: registerDto.lastName,
    });

    this.logger.log(`Successfully registered member: ${member.username}`);

    const responseData: MemberProfileResponseDto = {
      id: member.id,
      email: member.email,
      username: member.username,
      firstName: member.firstName,
      lastName: member.lastName,
      isActive: member.isActive,
      createdAt: member.createdAt,
      updatedAt: member.updatedAt,
    };

    return {
      success: true,
      data: responseData,
      message: 'Registration successful',
      meta: {
        timestamp: new Date().toISOString(),
        traceId: 'generated-trace-id', // This would be generated by interceptor
      },
    };
  }

  @Post('login')
  @HttpCode(HttpStatus.OK)
  async login(@Body() loginDto: MemberLoginDto): Promise<ApiSuccessResponse<MemberLoginResponseDto>> {
    this.logger.log(`Member login attempt for: ${loginDto.emailOrUsername}`);

    const authResult = await this.memberService.authenticateMember({
      emailOrUsername: loginDto.emailOrUsername,
      password: loginDto.password,
    });

    if (!authResult.isAuthenticated) {
      this.logger.warn(`Failed login attempt for: ${loginDto.emailOrUsername}`);
      throw new Error('Authentication failed');
    }

    // Generate JWT token
    const tokens = await this.jwtService.generateMemberToken(authResult.member.id);
    const expiresIn = 24 * 60 * 60; // 24 hours in seconds

    this.logger.log(`Successful member login for: ${authResult.member.username}`);

    const responseData: MemberLoginResponseDto = {
      id: authResult.member.id,
      email: authResult.member.email,
      username: authResult.member.username,
      firstName: authResult.member.firstName,
      lastName: authResult.member.lastName,
      accessToken: tokens.accessToken,
      expiresIn,
    };

    return {
      success: true,
      data: responseData,
      message: 'Login successful',
      meta: {
        timestamp: new Date().toISOString(),
        traceId: 'generated-trace-id', // This would be generated by interceptor
      },
    };
  }
}