# Override file for development environment
version: '3.8'

services:
  app-dev:
    environment:
      # Development-specific environment variables
      PORT: 3000
      CORS_ENABLED: "true"
      CORS_ORIGINS: "http://localhost:3000,http://localhost:3001,http://localhost:4200"
      RATE_LIMIT_TTL: 60
      RATE_LIMIT_LIMIT: 1000
      BCRYPT_ROUNDS: 4
      ENABLE_REQUEST_LOGGING: "true"
      ENABLE_RESPONSE_LOGGING: "true"
      ENABLE_ERROR_STACK_TRACE: "true"
      SLOW_QUERY_THRESHOLD: 500
      SLOW_REQUEST_THRESHOLD: 1000
      POINT_EXPIRATION_DAYS: 365
      ENABLE_POINT_EXPIRATION: "true"
      HEALTH_CHECK_ENABLED: "true"
      HEALTH_CHECK_DATABASE_ENABLED: "true"
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    command: ["npm", "run", "start:dev"]